#ifndef KOTERM_TERMINAL_COLORS_H
#define KOTERM_TERMINAL_COLORS_H

#include "koterm/terminal/Color.h"

#define DEFINE_SYS_COLOR(name, id) constexpr auto SYS_##name = Color::from_id(id)

namespace koterm::terminal::colors {

DEFINE_SYS_COLOR(BLACK, 30);
DEFINE_SYS_COLOR(RED, 31);
DEFINE_SYS_COLOR(GREEN, 32);
DEFINE_SYS_COLOR(YELLOW, 33);
DEFINE_SYS_COLOR(BLUE, 34);
DEFINE_SYS_COLOR(MAGENTA, 35);
DEFINE_SYS_COLOR(CYAN, 36);
DEFINE_SYS_COLOR(WHITE, 37);
DEFINE_SYS_COLOR(DEFAULT, 39);

DEFINE_SYS_COLOR(BRIGHT_BLACK, 90);
DEFINE_SYS_COLOR(BRIGHT_RED, 91);
DEFINE_SYS_COLOR(BRIGHT_GREEN, 92);
DEFINE_SYS_COLOR(BRIGHT_YELLOW, 93);
DEFINE_SYS_COLOR(BRIGHT_BLUE, 94);
DEFINE_SYS_COLOR(BRIGHT_MAGENTA, 95);
DEFINE_SYS_COLOR(BRIGHT_CYAN, 96);
DEFINE_SYS_COLOR(BRIGHT_WHITE, 97);

}

#undef DEFINE_SYS_COLOR

#endif
