# Project information
PROJECT_NAME = "koterm"

# Source directories
RECURSIVE = YES
INPUT = ./include/koterm

# Output directory
OUTPUT_DIRECTORY = ./docs/doxygen
CREATE_SUBDIRS = YES
CREATE_SUBDIRS_LEVEL = 8
OUTPUT_LANGUAGE = English

# Settings
DOXYFILE_ENCODING = UTF-8

EXTRACT_ALL = YES
EXTRACT_PRIVATE = YES
EXTRACT_STATIC = YES

EXCLUDE = ./tests,./examples
EXCLUDE_SYMBOLS = doctest::*

ENABLE_PREPROCESSING = YES
MACRO_EXPANSION = YES
EXPAND_ONLY_PREDEF = YES
PREDEFINED = "DEFINE_SYS_COLOR(name, id)=static constexpr auto SYS_##name = Color::from_code(id)"

# Style
GENERATE_TREEVIEW = YES
DISABLE_INDEX = NO
FULL_SIDEBAR = NO
HTML_EXTRA_STYLESHEET = ./vendor/doxygen-awesome/doxygen-awesome.css
HTML_COLORSTYLE = LIGHT
