#ifndef KOTERM_UTIL_ASCII_H
#define KOTERM_UTIL_ASCII_H

#include <cstdint>
namespace koterm::util::ascii {

enum codes : std::uint8_t {
    NUL                  = '\0',
    SOH                  = 1,
    STX                  = 2,
    ETX                  = 3,
    EOT                  = 4,
    ENQ                  = 5,
    ACK                  = 6,
    BEL                  = '\a',
    BACKSPACE            = '\b',
    TAB                  = '\t',
    NEWLINE              = '\n',
    VERTICAL_TAB         = '\v',
    PAGE_BREAK           = '\f',
    CR                   = '\r',
    SO                   = 14,
    SI                   = 15,
    DLE                  = 16,
    DC1                  = 17,
    DC2                  = 18,
    DC3                  = 19,
    DC4                  = 20,
    NAK                  = 21,
    SYN                  = 22,
    ETB                  = 23,
    CAN                  = 24,
    EM                   = 25,
    SUB                  = 26,
    ESC                  = '\x1B',
    FS                   = 28,
    GS                   = 29,
    RS                   = 30,
    US                   = 31,
    SPACE                = ' ',
    EXCLAMATION_MARK     = '!',
    DOUBLE_QUOTE         = '"',
    HASH                 = '#',
    DOLLAR               = '$',
    PERCENT              = '%',
    AMPERSAND            = '&',
    APOSTROPHE           = '\'',
    OPEN_PARENTHESIS     = '(',
    CLOSE_PARENTHESIS    = ')',
    ASTERISK             = '*',
    PLUS                 = '+',
    COMMA                = ',',
    MINUS                = '-',
    PERIOD               = '.',
    SLASH                = '/',
    DIGIT_0              = '0',
    DIGIT_1              = '1',
    DIGIT_2              = '2',
    DIGIT_3              = '3',
    DIGIT_4              = '4',
    DIGIT_5              = '5',
    DIGIT_6              = '6',
    DIGIT_7              = '7',
    DIGIT_8              = '8',
    DIGIT_9              = '9',
    COLON                = ':',
    SEMICOLON            = ';',
    LESS_THAN            = '<',
    EQUALS               = '=',
    GREATER_THAN         = '>',
    QUESTION_MARK        = '?',
    AT                   = '@',
    UPPERCASE_A          = 'A',
    UPPERCASE_B          = 'B',
    UPPERCASE_C          = 'C',
    UPPERCASE_D          = 'D',
    UPPERCASE_E          = 'E',
    UPPERCASE_F          = 'F',
    UPPERCASE_G          = 'G',
    UPPERCASE_H          = 'H',
    UPPERCASE_I          = 'I',
    UPPERCASE_J          = 'J',
    UPPERCASE_K          = 'K',
    UPPERCASE_L          = 'L',
    UPPERCASE_M          = 'M',
    UPPERCASE_N          = 'N',
    UPPERCASE_O          = 'O',
    UPPERCASE_P          = 'P',
    UPPERCASE_Q          = 'Q',
    UPPERCASE_R          = 'R',
    UPPERCASE_S          = 'S',
    UPPERCASE_T          = 'T',
    UPPERCASE_U          = 'U',
    UPPERCASE_V          = 'V',
    UPPERCASE_W          = 'W',
    UPPERCASE_X          = 'X',
    UPPERCASE_Y          = 'Y',
    UPPERCASE_Z          = 'Z',
    OPEN_SQUARE_BRACKET  = '[',
    BACKSLASH            = '\\',
    CLOSE_SQUARE_BRACKET = ']',
    CARET                = '^',
    UNDERSCORE           = '_',
    BACKTICK             = '`',
    LOWERCASE_A          = 'a',
    LOWERCASE_B          = 'b',
    LOWERCASE_C          = 'c',
    LOWERCASE_D          = 'd',
    LOWERCASE_E          = 'e',
    LOWERCASE_F          = 'f',
    LOWERCASE_G          = 'g',
    LOWERCASE_H          = 'h',
    LOWERCASE_I          = 'i',
    LOWERCASE_J          = 'j',
    LOWERCASE_K          = 'k',
    LOWERCASE_L          = 'l',
    LOWERCASE_M          = 'm',
    LOWERCASE_N          = 'n',
    LOWERCASE_O          = 'o',
    LOWERCASE_P          = 'p',
    LOWERCASE_Q          = 'q',
    LOWERCASE_R          = 'r',
    LOWERCASE_S          = 's',
    LOWERCASE_T          = 't',
    LOWERCASE_U          = 'u',
    LOWERCASE_V          = 'v',
    LOWERCASE_W          = 'w',
    LOWERCASE_X          = 'x',
    LOWERCASE_Y          = 'y',
    LOWERCASE_Z          = 'z',
    OPEN_CURLY_BRACE     = '{',
    PIPE                 = '|',
    CLOSE_CURLY_BRACE    = '}',
    TILDE                = '~',
    DEL                  = 127,
    INVALID              = 128,
};

constexpr char END_SPECIAL = 32;

}

#endif
